version: "3"
services:
    server:
        build: 
            context: .
            dockerfile: docker-files/Dockerfile
        volumes:
            - ./src:/var/www/html
        ports:
            - 80:8000
        environment:
            - TZ=UTC
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=MySQLPassw0rd
        ports:
            - 3306:3306
    redis:
        image: isaackuang/redis
        ports:
            - 6379:6379
